language: php

php:
    - 7.2
    - hhvm

before_script:
    - composer self-update
    - composer install --prefer-source

script:
    - ./vendor/bin/phpunit

matrix:
    allow_failures:
        - php: hhvm

branches:
    only:
        - master
        - develop
